export type Framework = "next-react" | "react-vite" | "static-html";
// Drives which mock "live preview" layout a project renders — lets sample
// projects and templates actually look like what their name promises,
// instead of every project sharing one generic inventory dashboard.
export type PreviewKind =
  | "inventory"
  | "team"
  | "finance"
  | "crm"
  | "ecommerce"
  | "analytics"
  | "saas"
  | "legal"
  | "healthcare"
  | "portfolio"
  // Used specifically for projects generated by a real AI call against
  // arbitrary, unpredictable content — see live-preview.tsx for why this
  // renders an honest placeholder instead of one of the canned mockups
  // above (those are only accurate for BuildAI's own fixed demo content
  // and templates, not for whatever an AI just generated from scratch).
  | "custom";

export interface Project {
  id: string;
  name: string;
  description: string;
  framework: Framework;
  accentHue: number;
  previewKind: PreviewKind;
  createdAt: string;
  updatedAt: string;
  status: "ready" | "generating" | "error";
  /** false while a template is being customized but not yet added to "Your projects". */
  saved: boolean;
  /**
   * True only for projects actually created via a real backend call (see
   * hydrateGeneratedProject in store.ts) — false for local/demo/template
   * projects, which don't exist as real rows in the database at all. The
   * AI chat panel checks this before attempting a real chat-edit API call,
   * since sending one for a project the backend has never heard of would
   * just fail with a foreign-key error.
   */
  remote: boolean;
}

export interface ProjectFile {
  id: string;
  path: string;
  content: string;
  language: string;
}

export type ChatRole = "user" | "assistant" | "system";

export interface ChatMessage {
  id: string;
  role: ChatRole;
  content: string;
  createdAt: string;
  status?: "streaming" | "done" | "error" | "cancelled";
}

export interface ProjectVersion {
  id: string;
  number: number;
  label: string;
  description: string;
  createdAt: string;
  fileCount: number;
}

export interface Template {
  id: string;
  name: string;
  description: string;
  category: "Dashboard" | "SaaS" | "Portfolio" | "E-commerce" | "CRM" | "Legal" | "Healthcare" | "Finance";
  accentHue: number;
  previewKind: PreviewKind;
  files: Omit<ProjectFile, "id">[];
}
